// buttons for keyboard
const allButtons = {
  Backquote: {
    keyCode: 220,
    key: { normal: { en: "`", ru: "ё" }, shifted: { en: "~", ru: "Ë" } },
    width: "100",
    type: "print",
  },
  Digit1: {
    keyCode: 49,
    key: { normal: { en: "1", ru: "1" }, shifted: { en: "!", ru: "!" } },
    width: "100",
    type: "print",
  },
  Digit2: {
    keyCode: 50,
    key: { normal: { en: "2", ru: "2" }, shifted: { en: "@", ru: '"' } },
    width: "100",
    type: "print",
  },
  Digit3: {
    keyCode: 51,
    key: { normal: { en: "3", ru: "3" }, shifted: { en: "#", ru: "№" } },
    width: "100",
    type: "print",
  },
  Digit4: {
    keyCode: 52,
    key: { normal: { en: "4", ru: "4" }, shifted: { en: "$", ru: ";" } },
    width: "100",
    type: "print",
  },
  Digit5: {
    keyCode: 53,
    key: { normal: { en: "5", ru: "5" }, shifted: { en: "%", ru: "%" } },
    width: "100",
    type: "print",
  },
  Digit6: {
    keyCode: 54,
    key: { normal: { en: "6", ru: "6" }, shifted: { en: "^", ru: ":" } },
    width: "100",
    type: "print",
  },
  Digit7: {
    keyCode: 55,
    key: { normal: { en: "7", ru: "7" }, shifted: { en: "&", ru: "?" } },
    width: "100",
    type: "print",
  },
  Digit8: {
    keyCode: 56,
    key: { normal: { en: "8", ru: "8" }, shifted: { en: "*", ru: "*" } },
    width: "100",
    type: "print",
  },
  Digit9: {
    keyCode: 57,
    key: { normal: { en: "9", ru: "9" }, shifted: { en: "(", ru: "(" } },
    width: "100",
    type: "print",
  },
  Digit0: {
    keyCode: 48,
    key: { normal: { en: "0", ru: "0" }, shifted: { en: ")", ru: ")" } },
    width: "100",
    type: "print",
  },
  Minus: {
    keyCode: 189,
    key: { normal: { en: "-", ru: "-" }, shifted: { en: "_", ru: "_" } },
    width: "100",
    type: "print",
  },
  Equal: {
    keyCode: 187,
    key: { normal: { en: "=", ru: "=" }, shifted: { en: "+", ru: "+" } },
    width: "100",
    type: "print",
  },
  Backspace: {
    keyCode: 8,
    key: {
      normal: { en: "Backspace", ru: "Backspace" },
      shifted: { en: "Backspace", ru: "Backspace" },
    },
    width: "200",
    type: "func",
  },
  Tab: {
    keyCode: 9,
    key: {
      normal: { en: "Tab", ru: "Tab" },
      shifted: { en: "Tab", ru: "Tab" },
    },
    width: "125",
    type: "func",
  },
  KeyQ: {
    keyCode: 81,
    key: { normal: { en: "q", ru: "й" }, shifted: { en: "Q", ru: "Й" } },
    width: "100",
    type: "print",
  },
  KeyW: {
    keyCode: 87,
    key: { normal: { en: "w", ru: "ц" }, shifted: { en: "W", ru: "Ц" } },
    width: "100",
    type: "print",
  },
  KeyE: {
    keyCode: 69,
    key: { normal: { en: "e", ru: "у" }, shifted: { en: "E", ru: "У" } },
    width: "100",
    type: "print",
  },
  KeyR: {
    keyCode: 82,
    key: { normal: { en: "r", ru: "к" }, shifted: { en: "R", ru: "К" } },
    width: "100",
    type: "print",
  },
  KeyT: {
    keyCode: 84,
    key: { normal: { en: "t", ru: "е" }, shifted: { en: "T", ru: "Е" } },
    width: "100",
    type: "print",
  },
  KeyY: {
    keyCode: 89,
    key: { normal: { en: "y", ru: "н" }, shifted: { en: "Y", ru: "Н" } },
    width: "100",
    type: "print",
  },
  KeyU: {
    keyCode: 85,
    key: { normal: { en: "u", ru: "г" }, shifted: { en: "U", ru: "Г" } },
    width: "100",
    type: "print",
  },
  KeyI: {
    keyCode: 73,
    key: { normal: { en: "i", ru: "ш" }, shifted: { en: "I", ru: "Ш" } },
    width: "100",
    type: "print",
  },
  KeyO: {
    keyCode: 79,
    key: { normal: { en: "o", ru: "щ" }, shifted: { en: "O", ru: "Щ" } },
    width: "100",
    type: "print",
  },
  KeyP: {
    keyCode: 80,
    key: { normal: { en: "p", ru: "з" }, shifted: { en: "P", ru: "З" } },
    width: "100",
    type: "print",
  },
  BracketLeft: {
    keyCode: 219,
    key: { normal: { en: "[", ru: "х" }, shifted: { en: "{", ru: "Х" } },
    width: "100",
    type: "print",
  },
  BracketRight: {
    keyCode: 221,
    key: { normal: { en: "]", ru: "ъ" }, shifted: { en: "}", ru: "Ъ" } },
    width: "100",
    type: "print",
  },
  Backslash: {
    keyCode: 220,
    key: { normal: { en: "\\", ru: "\\" }, shifted: { en: "|", ru: "/" } },
    width: "100",
    type: "print",
  },
  NumpadDecimal: {
    keyCode: 46,
    key: {
      normal: { en: "Del", ru: "Del" },
      shifted: { en: "Del", ru: "Del" },
    },
    width: "125",
    type: "func",
  },
  CapsLock: {
    keyCode: 20,
    key: {
      normal: { en: "Capslock", ru: "Capslock" },
      shifted: { en: "Capslock", ru: "Capslock" },
    },
    width: "200",
    type: "func",
  },
  KeyA: {
    keyCode: 65,
    key: { normal: { en: "a", ru: "ф" }, shifted: { en: "A", ru: "Ф" } },
    width: "100",
    type: "print",
  },
  KeyS: {
    keyCode: 83,
    key: { normal: { en: "s", ru: "ы" }, shifted: { en: "S", ru: "Ы" } },
    width: "100",
    type: "print",
  },
  KeyD: {
    keyCode: 68,
    key: { normal: { en: "d", ru: "в" }, shifted: { en: "D", ru: "В" } },
    width: "100",
    type: "print",
  },
  KeyF: {
    keyCode: 70,
    key: { normal: { en: "f", ru: "а" }, shifted: { en: "F", ru: "А" } },
    width: "100",
    type: "print",
  },
  KeyG: {
    keyCode: 71,
    key: { normal: { en: "g", ru: "п" }, shifted: { en: "G", ru: "П" } },
    width: "100",
    type: "print",
  },
  KeyH: {
    keyCode: 72,
    key: { normal: { en: "h", ru: "р" }, shifted: { en: "H", ru: "Р" } },
    width: "100",
    type: "print",
  },
  KeyJ: {
    keyCode: 74,
    key: { normal: { en: "j", ru: "о" }, shifted: { en: "J", ru: "О" } },
    width: "100",
    type: "print",
  },
  KeyK: {
    keyCode: 75,
    key: { normal: { en: "k", ru: "л" }, shifted: { en: "K", ru: "Л" } },
    width: "100",
    type: "print",
  },
  KeyL: {
    keyCode: 76,
    key: { normal: { en: "l", ru: "д" }, shifted: { en: "L", ru: "Д" } },
    width: "100",
    type: "print",
  },
  Semicolon: {
    keyCode: 186,
    key: { normal: { en: ";", ru: "ж" }, shifted: { en: ":", ru: "Ж" } },
    width: "100",
    type: "print",
  },
  Quote: {
    keyCode: 222,
    key: { normal: { en: "'", ru: "э" }, shifted: { en: '"', ru: "Э" } },
    width: "100",
    type: "print",
  },
  Enter: {
    keyCode: 13,
    key: {
      normal: { en: "Enter", ru: "Enter" },
      shifted: { en: "Enter", ru: "Enter" },
    },
    width: "200",
    type: "func",
  },
  ShiftLeft: {
    keyCode: 16,
    key: {
      normal: { en: "Shift", ru: "Shift" },
      shifted: { en: "Shift", ru: "Shift" },
    },
    width: "200",
    type: "func",
  },
  KeyZ: {
    keyCode: 90,
    key: { normal: { en: "z", ru: "я" }, shifted: { en: "Z", ru: "Я" } },
    width: "100",
    type: "print",
  },
  KeyX: {
    keyCode: 88,
    key: { normal: { en: "x", ru: "ч" }, shifted: { en: "X", ru: "Ч" } },
    width: "100",
    type: "print",
  },
  KeyC: {
    keyCode: 67,
    key: { normal: { en: "c", ru: "с" }, shifted: { en: "C", ru: "С" } },
    width: "100",
    type: "print",
  },
  KeyV: {
    keyCode: 86,
    key: { normal: { en: "v", ru: "м" }, shifted: { en: "V", ru: "М" } },
    width: "100",
    type: "print",
  },
  KeyB: {
    keyCode: 66,
    key: { normal: { en: "b", ru: "и" }, shifted: { en: "B", ru: "И" } },
    width: "100",
    type: "print",
  },
  KeyN: {
    keyCode: 78,
    key: { normal: { en: "n", ru: "т" }, shifted: { en: "N", ru: "Т" } },
    width: "100",
    type: "print",
  },
  KeyM: {
    keyCode: 77,
    key: { normal: { en: "m", ru: "ь" }, shifted: { en: "M", ru: "Ь" } },
    width: "100",
    type: "print",
  },
  Comma: {
    keyCode: 188,
    key: { normal: { en: ",", ru: "б" }, shifted: { en: "<", ru: "Б" } },
    width: "100",
    type: "print",
  },
  Period: {
    keyCode: 190,
    key: { normal: { en: ".", ru: "ю" }, shifted: { en: ">", ru: "Ю" } },
    width: "100",
    type: "print",
  },
  Slash: {
    keyCode: 191,
    key: { normal: { en: "/", ru: "." }, shifted: { en: "?", ru: "," } },
    width: "100",
    type: "print",
  },
  ArrowUp: {
    keyCode: 38,
    key: { normal: { en: "△", ru: "△" }, shifted: { en: "△", ru: "△" } },
    width: "100",
    type: "print",
  },
  ShiftRight: {
    keyCode: 16,
    key: {
      normal: { en: "Shift", ru: "Shift" },
      shifted: { en: "Shift", ru: "Shift" },
    },
    width: "200",
    type: "func",
  },
  ControlLeft: {
    keyCode: 17,
    key: {
      normal: { en: "Ctrl", ru: "Ctrl" },
      shifted: { en: "Ctrl", ru: "Ctrl" },
    },
    width: "100",
    type: "func",
  },
  OSLeft: {
    keyCode: 91,
    key: {
      normal: { en: "Win", ru: "Win" },
      shifted: { en: "Win", ru: "Win" },
    },
    width: "100",
    type: "func",
  },
  AltLeft: {
    keyCode: 18,
    key: {
      normal: { en: "Alt", ru: "Alt" },
      shifted: { en: "Alt", ru: "Alt" },
    },
    width: "100",
    type: "func",
  },
  Space: {
    keyCode: 32,
    key: { normal: { en: " ", ru: " " }, shifted: { en: " ", ru: " " } },
    width: "700",
    type: "print",
  },
  AltRight: {
    keyCode: 18,
    key: {
      normal: { en: "Alt", ru: "Alt" },
      shifted: { en: "Alt", ru: "Alt" },
    },
    width: "100",
    type: "func",
  },
  ArrowLeft: {
    keyCode: 37,
    key: { normal: { en: "◁", ru: "◁" }, shifted: { en: "◁", ru: "◁" } },
    width: "100",
    type: "print",
  },
  ArrowDown: {
    keyCode: 40,
    key: { normal: { en: "▽", ru: "▽" }, shifted: { en: "▽", ru: "▽" } },
    width: "100",
    type: "print",
  },
  ArrowRight: {
    keyCode: 39,
    key: { normal: { en: "▷", ru: "▷" }, shifted: { en: "▷", ru: "▷" } },
    width: "100",
    type: "print",
  },
  ControlRight: {
    keyCode: 17,
    key: {
      normal: { en: "Ctrl", ru: "Ctrl" },
      shifted: { en: "Ctrl", ru: "Ctrl" },
    },
    width: "100",
    type: "func",
  },
};

export default allButtons;
